export const padsandinks = [
  {
    id: 1,
    name: "Stamp Pads",
    desc: "High-quality ink pads for clear and consistent impressions.",
    slug: "stamp-pads",
    img: "/padsandinks-img1.png",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 2,
    name: "Ink Refills",
    desc: "Premium refill inks for long-lasting stamp performance.",
    slug: "ink-refills",
    img: "/padsandinks-img2.png",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 3,
    name: "Trodat Ink",
    desc: "Original Trodat ink for professional stamping results.",
    slug: "trodat-ink",
    img: "/padsandinks-img3.png",
    rating: 4.9,
    reviews: 210,
  },
  {
    id: 4,
    name: "Color Ink Pads",
    desc: "Available in multiple colors for versatile stamping needs.",
    slug: "color-ink-pads",
    img: "/padsandinks-img4.png",
    rating: 4.6,
    reviews: 74,
  },
  {
    id: 5,
    name: "Quick-Dry Inks",
    desc: "Fast drying inks ideal for office and industrial use.",
    slug: "quick-dry-inks",
    img: "/padsandinks-img5.png",
    rating: 4.8,
    reviews: 134,
  },
];
