export const rubberstamps = [
  {
    id: 1,
    name: "Rubber Stamps",
    desc: "High-quality traditional rubber stamps for daily use.",
    slug: "rubber-stamps",
    img: "/rubberstamp-img1.png",
    rating: 4.8,
    reviews: 142,
  },
  {
    id: 2,
    name: "Wooden Handle Stamps",
    desc: "Classic wooden handle stamps for precise impressions.",
    slug: "wooden-handle-stamps",
    img: "/rubberstamp-img2.png",
    rating: 4.7,
    reviews: 67,
  },
  {
    id: 3,
    name: "Custom Rubber Stamps",
    desc: "Personalized rubber stamps with your own design.",
    slug: "custom-rubber-stamps",
    img: "/rubberstamp-img3.png",
    rating: 4.9,
    reviews: 289,
  },
  {
    id: 4,
    name: "Office Rubber Stamps",
    desc: "Ideal stamps for office and business use.",
    slug: "office-rubber-stamps",
    img: "/rubberstamp-img4.png",
    rating: 4.6,
    reviews: 54,
  },
  {
    id: 5,
    name: "Date Rubber Stamps",
    desc: "Rubber stamps with adjustable date settings.",
    slug: "date-rubber-stamps",
    img: "/rubberstamp-img5.png",
    rating: 4.8,
    reviews: 112,
  },
];
