export const trodatprinty = [
  {
    id: 1,
    name: "Printy Stamps",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    slug: "printy-stamps",
    img: "/trodatprinty-img1.png",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 2,
    name: "Printy Daters",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    slug: "printy-daters",
    img: "/trodatprinty-img2.png",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 3,
    name: "Non-Self Inking Daters",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    slug: "non-self-inking-daters",
    img: "/trodatprinty-img3.png",
    rating: 4.6,
    reviews: 42,
  },
  {
    id: 4,
    name: "Professional Line",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    slug: "professional-line",
    img: "/trodatprinty-img4.png",
    rating: 4.9,
    reviews: 210,
  },
  {
    id: 5,
    name: "Stock Stamps",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    slug: "stock-stamps",
    img: "/trodatprinty-img5.png",
    rating: 4.8,
    reviews: 134,
  },
];
