export const giftBoxes = [
  {
    id: 1,
    name: "Classic Luxury Gift Box",
    desc: "Elegant gift box with premium finishing, perfect for any occasion.",
    img: "/giftbox-1.png",
    price: 1499,
    reviews: 320,
    sizes: ["Small", "Medium", "Large"],
    colors: ["Red", "Gold", "White"],
    slug: "classic-luxury-gift-box-1",
    category: "Gift Boxes",
  },
  {
    id: 2,
    name: "Eco-Friendly Gift Box",
    desc: "Sustainable and reusable gift box made with eco-friendly materials.",
    img: "/giftbox-2.png",
    price: 1299,
    reviews: 210,
    sizes: ["Medium", "Large"],
    colors: ["Brown", "Green", "Natural"],
    slug: "eco-friendly-gift-box-2",
    category: "Gift Boxes",
  },
  {
    id: 3,
    name: "Chocolate & Treats Box",
    desc: "Deluxe gift box filled with assorted chocolates and snacks.",
    img: "/giftbox-3.png",
    price: 1599,
    reviews: 410,
    sizes: ["Small", "Medium"],
    colors: ["Red", "Brown", "Gold"],
    slug: "chocolate-treats-box-3",
    category: "Gift Boxes",
  },
  {
    id: 4,
    name: "Festive Celebration Box",
    desc: "Bright and festive gift box ideal for celebrations and festivals.",
    img: "/giftbox-4.png",
    price: 1399,
    reviews: 275,
    sizes: ["Medium", "Large"],
    colors: ["Yellow", "Red", "Green"],
    slug: "festive-celebration-box-4",
    category: "Gift Boxes",
  },
  {
    id: 5,
    name: "Premium Personalized Box",
    desc: "Customizable gift box where you can add names or messages.",
    img: "/giftbox-5.png",
    price: 1799,
    reviews: 190,
    sizes: ["Small", "Medium", "Large"],
    colors: ["White", "Black", "Silver"],
    slug: "premium-personalized-box-5",
    category: "Gift Boxes",
  },
];
