export const mugsAndBottles = [
  {
    id: 1,
    name: "Classic Ceramic Mug",
    desc: "Customizable ceramic mug, perfect for coffee or tea lovers.",
    img: "/mug-1.png",
    price: 699,
    reviews: 220,
    sizes: ["250ml", "350ml"],
    colors: ["White", "Black", "Blue"],
    slug: "classic-ceramic-mug-1",
    category: "Mugs & Bottles",
  },
  {
    id: 2,
    name: "Travel Thermo Mug",
    desc: "Insulated travel mug to keep your drinks hot or cold on the go.",
    img: "/mug-2.png",
    price: 899,
    reviews: 180,
    sizes: ["350ml", "500ml"],
    colors: ["Black", "Silver", "Red"],
    slug: "travel-thermo-mug-2",
    category: "Mugs & Bottles",
  },
  {
    id: 3,
    name: "Glass Bottle",
    desc: "Reusable glass bottle with customizable name or design.",
    img: "/mug-3.png",
    price: 1099,
    reviews: 150,
    sizes: ["500ml", "750ml"],
    colors: ["Clear", "Blue", "Green"],
    slug: "personalized-glass-bottle-3",
    category: "Mugs & Bottles",
  },
  {
    id: 4,
    name: "Stainless Steel Bottle",
    desc: "Durable and stylish stainless steel bottle for everyday use.",
    img: "/mug-4.png",
    price: 1299,
    reviews: 200,
    sizes: ["500ml", "1L"],
    colors: ["Silver", "Black", "Matte Red"],
    slug: "stainless-steel-bottle-4",
    category: "Mugs & Bottles",
  },
  {
    id: 5,
    name: "Color-Changing Mug",
    desc: "Ceramic mug that reveals your custom design when hot liquid is added.",
    img: "/mug-5.png",
    price: 899,
    reviews: 170,
    sizes: ["300ml", "400ml"],
    colors: ["White", "Black"],
    slug: "magic-color-changing-mug-5",
    category: "Mugs & Bottles",
  },
];
