export const pensNotebooks = [
  {
    id: 1,
    name: "Executive Metal Pen",
    desc: "Premium metal pen with smooth ink flow for professional use.",
    img: "/pens-1.png",
    price: 499,
    reviews: 120,
    colors: ["Silver", "Black", "Gold"],
    slug: "executive-metal-pen-1",
    category: "Pens & Notebooks",
  },
  {
    id: 2,
    name: "Luxury Rollerball Pen",
    desc: "Elegant rollerball pen with ergonomic design and refillable ink.",
    img: "/pens-2.png",
    price: 699,
    reviews: 90,
    colors: ["Black", "Blue", "Red"],
    slug: "luxury-rollerball-pen-2",
    category: "Pens & Notebooks",
  },
  {
    id: 3,
    name: "Classic Hardcover Notebook",
    desc: "Durable hardcover notebook with lined pages, ideal for journaling.",
    img: "/pens-3.png",
    price: 599,
    reviews: 140,
    colors: ["Black", "Brown", "Navy"],
    slug: "classic-hardcover-notebook-3",
    category: "Pens & Notebooks",
  },
  {
    id: 4,
    name: "Spiral Bound Notebook",
    desc: "Convenient spiral notebook with high-quality paper for daily notes.",
    img: "/pens-1.png",
    price: 349,
    reviews: 110,
    colors: ["White", "Black", "Grey"],
    slug: "spiral-bound-notebook-4",
    category: "Pens & Notebooks",
  },
  {
    id: 5,
    name: "Luxury Fountain Pen",
    desc: "Smooth-writing fountain pen with refillable ink and elegant design.",
    img: "/pens-5.png",
    price: 999,
    reviews: 75,
    colors: ["Black", "Silver"],
    slug: "luxury-fountain-pen-5",
    category: "Pens & Notebooks",
  },
];
