export const techGifts = [
  {
    id: 1,
    name: "Wireless Bluetooth Earbuds",
    desc: "Compact and high-quality sound earbuds with long battery life.",
    img: "/tech-1.png",
    price: 2499,
    reviews: 320,
    colors: ["Black", "White", "Blue"],
    slug: "wireless-bluetooth-earbuds-1",
    category: "Tech Gifts",
  },
  {
    id: 2,
    name: "Portable Power Bank",
    desc: "Slim and powerful power bank to charge your devices on the go.",
    img: "/tech-2.png",
    price: 1999,
    reviews: 280,
    colors: ["Black", "Silver", "Red"],
    slug: "portable-power-bank-10000mah-2",
    category: "Tech Gifts",
  },
  {
    id: 3,
    name: "Smart LED Desk Lamp",
    desc: "Adjustable brightness desk lamp with touch control and USB charging.",
    img: "/tech-3.png",
    price: 1799,
    reviews: 150,
    colors: ["White", "Black"],
    slug: "smart-led-desk-lamp-3",
    category: "Tech Gifts",
  },
  {
    id: 4,
    name: "Wireless Mouse",
    desc: "Ergonomic wireless mouse suitable for work and gaming.",
    img: "/tech-1.png",
    price: 899,
    reviews: 210,
    colors: ["Black", "Grey", "Blue"],
    slug: "wireless-mouse-4",
    category: "Tech Gifts",
  },
  {
    id: 5,
    name: "USB-C Multiport Hub",
    desc: "Expand your laptop connectivity with multiple USB and HDMI ports.",
    img: "/tech-2.png",
    price: 1499,
    reviews: 180,
    colors: ["Silver", "Space Grey"],
    slug: "usb-c-multiport-hub-5",
    category: "Tech Gifts",
  },
];
