export const cap = [
  {
    id: 1,
    name: "Classic Baseball Cap",
    desc: "Adjustable cotton baseball cap.",
    img: "/cap-1.png",
    reviews: 150,
    sizes: ["One Size"],
    colors: ["Black", "White", "Navy"],
    slug: "classic-baseball-cap-1",
    category: "Caps",
  },
  {
    id: 2,
    name: "Snap Street Cap",
    desc: "Trendy snapback cap with flat brim for modern streetwear look.",
    img: "/cap-2.png",
    reviews: 220,
    sizes: ["One Size"],
    colors: ["Red", "Black", "Grey"],
    slug: "snapback-street-cap-2",
    category: "Caps",
  },
  {
    id: 3,
    name: "Sports Mesh Cap",
    desc: "Breathable mesh cap designed for running and outdoor sports.",
    img: "/cap-3.png",
    reviews: 95,
    sizes: ["One Size"],
    colors: ["Blue", "White", "Black"],
    slug: "sports-mesh-cap-3",
    category: "Caps",
  },
  {
    id: 4,
    name: "Vintage Trucker Cap",
    desc: "Retro trucker style cap with mesh back for ventilation.",
    img: "/cap-4.png",
    reviews: 130,
    sizes: ["One Size"],
    colors: ["Green", "Brown", "Beige"],
    slug: "vintage-trucker-cap-4",
    category: "Caps",
  },
  {
    id: 5,
    name: "Cotton Dad Cap",
    desc: "Soft washed cotton dad cap.",
    img: "/cap-5.png",
    reviews: 180,
    sizes: ["One Size"],
    colors: ["Grey", "Navy", "White"],
    slug: "cotton-dad-cap-5",
    category: "Caps",
  },
];
