export const jacket = [
  {
    id: 1,
    name: "Classic Denim Jacket",
    desc: "Stylish light-wash denim jacket perfect for everyday casual wear.",
    img: "/jacket-1.png",
    reviews: 410,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    slug: "classic-denim-jacket-1",
    category: "Jackets",
  },
  {
    id: 2,
    name: "Black Bomber Jacket",
    desc: "Lightweight bomber jacket with ribbed cuffs and modern streetwear fit.",
    img: "/jacket-2.png",
    reviews: 520,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Green"],
    slug: "black-bomber-jacket-2",
    category: "Jackets",
  },
  {
    id: 3,
    name: "Puffer Winter Jacket",
    desc: "Warm padded puffer jacket designed for colder weather.",
    img: "/jacket-3.png",
    reviews: 310,
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Olive", "Black"],
    slug: "puffer-winter-jacket-3",
    category: "Jackets",
  },
  {
    id: 4,
    name: "Leather Biker Jacket",
    desc: "Premium faux-leather biker jacket with metal detailing.",
    img: "/jacket-4.png",
    reviews: 185,
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    slug: "leather-biker-jacket-4",
    category: "Jackets",
  },
  {
    id: 5,
    name: "Windbreaker Jacket",
    desc: "Light and breathable windbreaker ideal for sports and outdoor activities.",
    img: "/jacket-5.png",
    reviews: 270,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue", "Grey"],
    slug: "sports-windbreaker-jacket-5",
    category: "Jackets",
  },
];
