export const paintShort = [
  {
    id: 1,
    name: "Acrylic Wall Paint",
    desc: "Premium acrylic paint for smooth, long-lasting wall finish.",
    img: "/paint-1.png",
    reviews: 210,
    sizes: ["1L", "5L", "10L"],
    colors: ["White"],
    slug: "acrylic-wall-paint-white-1",
    category: "Paints",
  },
  {
    id: 2,
    name: "Matte Interior Paint",
    desc: "Easy-to-apply interior paint with a vibrant matte finish.",
    img: "/paint-2.png",
    reviews: 180,
    sizes: ["1L", "5L"],
    colors: ["Blue"],
    slug: "matte-interior-paint-blue-2",
    category: "Paints",
  },
  {
    id: 3,
    name: "Glossy Enamel Paint",
    desc: "Durable enamel paint ideal for wooden and metal surfaces.",
    img: "/paint-3.png",
    reviews: 140,
    sizes: ["500ml", "1L"],
    colors: ["Red"],
    slug: "glossy-enamel-paint-red-3",
    category: "Paints",
  },
  {
    id: 4,
    name: "Waterproof Paint",
    desc: "Exterior paint resistant to water and sunlight for lasting protection.",
    img: "/paint-4.png",
    reviews: 230,
    sizes: ["1L", "5L", "10L"],
    colors: ["Green"],
    slug: "waterproof-exterior-paint-green-4",
    category: "Paints",
  },
  {
    id: 5,
    name: "Premium Oil Paint",
    desc: "High-quality oil-based paint for vibrant, smooth finish.",
    img: "/paint-5.png",
    reviews: 190,
    sizes: ["500ml", "1L"],
    colors: ["Yellow"],
    slug: "premium-oil-paint-yellow-5",
    category: "Paints",
  },
];
