export const shirt = [
  {
    id: 1,
    name: "Formal White Shirt",
    desc: "Classic cotton formal shirt, perfect for office and meetings.",
    img: "/shirt-1.png",
    reviews: 320,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue"],
    slug: "formal-white-shirt-1",
    category: "Shirts",
  },
  {
    id: 2,
    name: "Slim Fit Blue Shirt",
    desc: "Modern slim-fit shirt with breathable fabric for a sharp look.",
    img: "/shirt-2.png",
    reviews: 280,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Navy"],
    slug: "slim-fit-blue-shirt-2",
    category: "Shirts",
  },
  {
    id: 3,
    name: "Checked Casual Shirt",
    desc: "Comfortable checked shirt ideal for casual outings and weekends.",
    img: "/shirt-3.png",
    reviews: 200,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Green", "Blue"],
    slug: "checked-casual-shirt-3",
    category: "Shirts",
  },
  {
    id: 4,
    name: "Linen Summer Shirt",
    desc: "Lightweight linen shirt, perfect for hot weather and beach wear.",
    img: "/shirt-4.png",
    reviews: 150,
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "White"],
    slug: "linen-summer-shirt-4",
    category: "Shirts",
  },
  {
    id: 5,
    name: "Denim Work Shirt",
    desc: "Durable denim shirt with reinforced stitching, great for outdoor activities.",
    img: "/shirt-5.png",
    reviews: 180,
    sizes: ["M", "L", "XL"],
    colors: ["Denim Blue", "Black"],
    slug: "denim-work-shirt-5",
    category: "Shirts",
  },
];
