export const tshirt = [
  {
    id: 1,
    name: "Classic Black T-Shirt",
    desc: "Premium cotton T-shirt with a modern fit and soft feel.",
    img: "/tshirt-1.png",
    reviews: 220,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Grey"],
    slug: "classic-black-tshirt-1",
    category: "T-Shirts",
  },
  {
    id: 2,
    name: "Royal Blue T-Shirt",
    desc: "Vibrant blue T-shirt made with breathable fabric for daily wear.",
    img: "/tshirt-2.png",
    reviews: 180,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Navy", "White"],
    slug: "royal-blue-tshirt-2",
    category: "T-Shirts",
  },
  {
    id: 3,
    name: "Printed T-Shirt",
    desc: "Trendy graphic design T-shirt perfect for casual outings.",
    img: "/tshirt-3.png",
    reviews: 260,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red", "Green"],
    slug: "printed-graphic-tshirt-3",
    category: "T-Shirts",
  },
  {
    id: 4,
    name: "White Cotton T-Shirt",
    desc: "Soft and lightweight cotton shirt ideal for everyday use.",
    img: "/tshirt-4.png",
    reviews: 95,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    slug: "white-cotton-tshirt-4",
    category: "T-Shirts",
  },
  {
    id: 5,
    name: "Oversized T-Shirt",
    desc: "Oversized retro style T-shirt for a relaxed, trendy look.",
    img: "/tshirt-1.png",
    reviews: 310,
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "Brown", "Black"],
    slug: "vintage-oversized-tshirt-5",
    category: "T-Shirts",
  },
];
