// mugsAndBottles.js
export const bottles = [
  {
    id: 1,
    name: "Classic Ceramic Mug",
    slug: "classic-ceramic-mug",
    desc: "Sturdy ceramic mug with a glossy finish — perfect for hot beverages.",
    rating: 4.9,
    reviews: 120,
    img: "/mug-1.png",
  },
  {
    id: 2,
    name: "Travel Stainless Bottle",
    slug: "travel-stainless-bottle",
    desc: "Insulated stainless steel bottle keeps drinks hot or cold for hours.",
    rating: 4.8,
    reviews: 98,
    img: "/mug-2.png",
  },
  {
    id: 3,
    name: "Personalized Glass Bottle",
    slug: "personalized-glass-bottle",
    desc: "Elegant glass bottle that can be customized with a name or logo.",
    rating: 4.7,
    reviews: 85,
    img: "/mug-3.png",
  },
  {
    id: 4,
    name: "Eco-Friendly Bamboo Mug",
    slug: "eco-friendly-bamboo-mug",
    desc: "Reusable bamboo mug for a sustainable lifestyle.",
    rating: 4.6,
    reviews: 75,
    img: "/mug-4.png",
  },
  {
    id: 5,
    name: "Collapsible Travel Mug",
    slug: "collapsible-travel-mug",
    desc: "Space-saving travel mug that folds for easy storage.",
    rating: 4.7,
    reviews: 65,
    img: "/mug-5.png",
  },
  {
    id: 6,
    name: "Thermal Sport Bottle",
    slug: "thermal-sport-bottle",
    desc: "Perfect for workouts — keeps water cold for hours.",
    rating: 4.8,
    reviews: 110,
    img: "/mug-1.png",
  },
  {
    id: 7,
    name: "Double Wall Coffee Mug",
    slug: "double-wall-coffee-mug",
    desc: "Keeps your coffee hot without burning your hands.",
    rating: 4.9,
    reviews: 130,
    img: "/mug-2.png",
  },
  {
    id: 8,
    name: "Customized Travel Bottle",
    slug: "customized-travel-bottle",
    desc: "Personalized bottle — perfect for corporate gifting or giveaways.",
    rating: 4.8,
    reviews: 95,
    img: "/mug-3.png",
  },
  {
    id: 9,
    name: "Color Changing Mug",
    slug: "color-changing-mug",
    desc: "Watch your mug change color when hot liquid is poured in.",
    rating: 4.7,
    reviews: 80,
    img: "/mug-4.png",
  },
  {
    id: 10,
    name: "Premium Insulated Bottle",
    slug: "premium-insulated-bottle",
    desc: "High-quality insulated bottle — keeps drinks at perfect temperature.",
    rating: 4.9,
    reviews: 105,
    img: "/mug-5.png",
  },
];
