export const businessCards = [
  {
    id: 1,
    name: "Compact Cards",
    slug: "compact-cards",
    desc: "Small, sleek cards perfect for minimal branding and everyday use.",
    rating: 4.9,
    reviews: 12034,
    img: "/business-img1.png",
  },
  {
    id: 2,
    name: "Essential Cards",
    slug: "essential-cards",
    desc: "Standard business cards with a professional and clean finish.",
    rating: 4.8,
    reviews: 9872,
    img: "/business-img2.png",
  },
  {
    id: 3,
    name: "Wide Cards",
    slug: "wide-cards",
    desc: "Wider format cards for more space and bold designs.",
    rating: 4.7,
    reviews: 8451,
    img: "/business-img3.png",
  },
  {
    id: 4,
    name: "Standard Cards",
    slug: "standard-cards",
    desc: "Classic size cards suitable for all industries.",
    rating: 4.7,
    reviews: 7650,
    img: "/business-img4.png",
  },
  {
    id: 5,
    name: "Square Cards",
    slug: "square-cards",
    desc: "Modern square-shaped cards for a unique impression.",
    rating: 4.8,
    reviews: 6231,
    img: "/business-img5.png",
  },
  {
    id: 6,
    name: "Rounded Corner Cards",
    slug: "rounded-corner-cards",
    desc: "Smooth rounded edges for a soft and premium feel.",
    rating: 4.7,
    reviews: 5980,
    img: "/business-img6.png",
  },
  {
    id: 7,
    name: "Circle Cards",
    slug: "circle-cards",
    desc: "Creative circular cards that stand out instantly.",
    rating: 4.6,
    reviews: 4120,
    img: "/business-img7.png",
  },
  {
    id: 8,
    name: "Oval Cards",
    slug: "oval-cards",
    desc: "Elegant oval-shaped cards for stylish branding.",
    rating: 4.6,
    reviews: 3895,
    img: "/business-img8.png",
  },
  {
    id: 9,
    name: "Premium Cards",
    slug: "premium-cards",
    desc: "High-quality thick cards with luxurious finish.",
    rating: 4.9,
    reviews: 11023,
    img: "/business-img9.png",
  },
  {
    id: 10,
    name: "Matte Cards",
    slug: "matte-cards",
    desc: "Non-glossy cards with smooth and subtle texture.",
    rating: 4.7,
    reviews: 7021,
    img: "/business-img10.png",
  },
  {
    id: 11,
    name: "Glossy Cards",
    slug: "glossy-cards",
    desc: "Shiny finish cards for vibrant colors and images.",
    rating: 4.6,
    reviews: 6543,
    img: "/business-img11.png",
  },
  {
    id: 12,
    name: "Textured Cards",
    slug: "textured-cards",
    desc: "Premium textured surface for a tactile experience.",
    rating: 4.8,
    reviews: 4321,
    img: "/business-img12.png",
  },
  {
    id: 13,
    name: "Folded Cards",
    slug: "folded-cards",
    desc: "Double-sided foldable cards for extra information.",
    rating: 4.7,
    reviews: 3890,
    img: "/business-img13.png",
  },
  {
    id: 14,
    name: "Foil Accent Cards",
    slug: "foil-accent-cards",
    desc: "Metallic foil highlights for premium branding.",
    rating: 4.9,
    reviews: 5210,
    img: "/business-img14.png",
  },
  {
    id: 15,
    name: "Embossed Cards",
    slug: "embossed-cards",
    desc: "Raised print effect for a luxury feel.",
    rating: 4.8,
    reviews: 4785,
    img: "/business-img15.png",
  },
  {
    id: 16,
    name: "Transparent Cards",
    slug: "transparent-cards",
    desc: "Clear plastic cards for a modern unique look.",
    rating: 4.6,
    reviews: 2950,
    img: "/business-img16.png",
  },
];
