export const cardPrint = [
  {
    id: 1,
    name: "Flyers",
    slug: "flyers",
    desc: "Eye-catching promotional flyers perfect for events, offers, and marketing campaigns.",
    rating: 4.9,
    reviews: 15020,
    img: "/card-img1.png",
  },
  {
    id: 2,
    name: "Brochures",
    slug: "brochures",
    desc: "Tri-fold or bi-fold brochures ideal for showcasing detailed information attractively.",
    rating: 4.8,
    reviews: 11240,
    img: "/card-img2.png",
  },
  {
    id: 3,
    name: "Postcards",
    slug: "postcards",
    desc: "Bold, compact postcards designed for direct mail and brand promotions.",
    rating: 4.7,
    reviews: 9821,
    img: "/card-img3.png",
  },
  {
    id: 4,
    name: "Leaflets",
    slug: "leaflets",
    desc: "Lightweight handout leaflets great for mass distribution and quick promotions.",
    rating: 4.6,
    reviews: 8450,
    img: "/card-img4.png",
  },
  {
    id: 5,
    name: "Invitation Cards",
    slug: "invitation-cards",
    desc: "Elegant custom invitations for corporate events, launches, and ceremonies.",
    rating: 4.9,
    reviews: 7640,
    img: "/card-img1.png",
  },
  {
    id: 6,
    name: "Greeting Cards",
    slug: "greeting-cards",
    desc: "Premium greeting cards for festive wishes, client greetings, and celebrations.",
    rating: 4.8,
    reviews: 6890,
    img: "/card-img2.png",
  },
  {
    id: 7,
    name: "Booklets",
    slug: "booklets",
    desc: "Multi-page booklets suitable for catalogs, company profiles, and event programs.",
    rating: 4.7,
    reviews: 5310,
    img: "/card-img3.png",
  },
  {
    id: 8,
    name: "Menus",
    slug: "menus",
    desc: "High-quality restaurant menus with durable prints and beautiful layouts.",
    rating: 4.7,
    reviews: 4980,
    img: "/card-img4.png",
  },
  {
    id: 9,
    name: "Table Tents",
    slug: "table-tents",
    desc: "Stand-up table tents perfect for food promotions, offers, and product highlights.",
    rating: 4.8,
    reviews: 4620,
    img: "/card-img1.png",
  },
  {
    id: 10,
    name: "Rack Cards",
    slug: "rack-cards",
    desc: "Tall promotional cards ideal for travel agencies, hotels, and boutiques.",
    rating: 4.7,
    reviews: 4350,
    img: "/card-img2.png",
  },
  {
    id: 11,
    name: "Door Hangers",
    slug: "door-hangers",
    desc: "Custom door hangers suitable for hotels, marketing, and brand messaging.",
    rating: 4.6,
    reviews: 3890,
    img: "/card-img3.png",
  },
  {
    id: 12,
    name: "Event Tickets",
    slug: "event-tickets",
    desc: "Printed event tickets with perforations and unique numbering options.",
    rating: 4.8,
    reviews: 3710,
    img: "/card-img4.png",
  },
  {
    id: 13,
    name: "Calendars",
    slug: "calendars",
    desc: "Custom desk and wall calendars ideal for yearly corporate giveaways.",
    rating: 4.7,
    reviews: 3400,
    img: "/card-img1.png",
  },
  {
    id: 14,
    name: "Certificates",
    slug: "certificates",
    desc: "Award and achievement certificates with premium printing and finishing.",
    rating: 4.9,
    reviews: 3250,
    img: "/card-img2.png",
  },
  {
    id: 15,
    name: "Notepads",
    slug: "notepads",
    desc: "Branded notepads perfect for corporate gifting and office use.",
    rating: 4.6,
    reviews: 2980,
    img: "/card-img3.png",
  },
  {
    id: 16,
    name: "Thank You Cards",
    slug: "thank-you-cards",
    desc: "Personalized thank-you cards to strengthen customer relationships.",
    rating: 4.7,
    reviews: 2700,
    img: "/card-img4.png",
  },
];
