export const fullSleeve = [
  {
    id: 1,
    name: "Classic White Full Sleeve",
    slug: "classic-white-full-sleeve",
    desc: "Soft cotton t-shirt with a timeless fit — perfect for every occasion.",
    rating: 4.9,
    reviews: 1523,
    img: "/t-shirt2.png",
  },
  {
    id: 2,
    name: "Black Crew Neck Full Sleeve",
    slug: "black-crew-neck-full-sleeve",
    desc: "Sleek black crew neck t-shirt, versatile and comfortable.",
    rating: 4.8,
    reviews: 1345,
    img: "/t-shirt2.png",
  },
  {
    id: 3,
    name: "Striped Full Sleeve",
    slug: "striped-full-sleeve",
    desc: "Casual striped t-shirt that adds style to everyday wear.",
    rating: 4.7,
    reviews: 1120,
    img: "/t-shirt2.png",
  },
  {
    id: 4,
    name: "V-Neck Full Sleeve",
    slug: "v-neck-full-sleeve",
    desc: "Lightweight v-neck t-shirt for a relaxed yet polished look.",
    rating: 4.8,
    reviews: 980,
    img: "/t-shirt2.png",
  },
  {
    id: 5,
    name: "Graphic Print Full Sleeve",
    slug: "graphic-print-full-sleeve",
    desc: "Trendy graphic print t-shirt to express your personality.",
    rating: 4.7,
    reviews: 860,
    img: "/t-shirt2.png",
  },
  {
    id: 6,
    name: "Longline Full Sleeve",
    slug: "longline-full-sleeve",
    desc: "Extended length t-shirt for a modern streetwear vibe.",
    rating: 4.6,
    reviews: 740,
    img: "/t-shirt2.png",
  },
  {
    id: 7,
    name: "Organic Cotton Full Sleeve",
    slug: "organic-cotton-full-sleeve",
    desc: "Eco-friendly organic cotton t-shirt — soft and sustainable.",
    rating: 4.9,
    reviews: 620,
    img: "/t-shirt2.png",
  },
  {
    id: 8,
    name: "Pocket Full Sleeve",
    slug: "pocket-full-sleeve",
    desc: "Casual t-shirt with a small chest pocket for style and function.",
    rating: 4.7,
    reviews: 540,
    img: "/t-shirt2.png",
  },
  {
    id: 9,
    name: "Athletic Fit Full Sleeve",
    slug: "athletic-fit-full-sleeve",
    desc: "Tailored t-shirt with a sporty cut — ideal for workouts.",
    rating: 4.8,
    reviews: 410,
    img: "/t-shirt2.png",
  },
  {
    id: 10,
    name: "Henley Full Sleeve",
    slug: "henley-full-sleeve",
    desc: "Classic henley t-shirt with buttoned placket for a rugged style.",
    rating: 4.6,
    reviews: 380,
    img: "/t-shirt2.png",
  },
  {
    id: 11,
    name: "Ringer Full Sleeve",
    slug: "ringer-full-sleeve",
    desc: "Retro-inspired t-shirt with contrast collar and sleeve edges.",
    rating: 4.7,
    reviews: 355,
    img: "/t-shirt2.png",
  },
  {
    id: 12,
    name: "Pocket Stripe Full Sleeve",
    slug: "pocket-stripe-full-sleeve",
    desc: "Striped t-shirt with chest pocket detail for casual flair.",
    rating: 4.8,
    reviews: 330,
    img: "/t-shirt2.png",
  },
  {
    id: 13,
    name: "Sleeveless Full Sleeve",
    slug: "sleeveless-full-sleeve",
    desc: "Cool and breathable t-shirt for layering under jackets.",
    rating: 4.6,
    reviews: 305,
    img: "/t-shirt2.png",
  },
  {
    id: 14,
    name: "Tie-Dye Full Sleeve",
    slug: "tie-dye-full-sleeve",
    desc: "Colorful tie-dye t-shirt for a fun, laid-back look.",
    rating: 4.9,
    reviews: 290,
    img: "/t-shirt2.png",
  },
  {
    id: 15,
    name: "Soft Modal Full Sleeve",
    slug: "soft-modal-full-sleeve",
    desc: "Premium modal fabric t-shirt — silky smooth and light.",
    rating: 4.8,
    reviews: 275,
    img: "/t-shirt2.png",
  },
  {
    id: 16,
    name: "Oversized Full Sleeve",
    slug: "oversized-full-sleeve",
    desc: "Relaxed oversized t-shirt for comfort and street style vibes.",
    rating: 4.7,
    reviews: 260,
    img: "/t-shirt2.png",
  },
];
