// giftBoxes.js
export const gift = [
  {
    id: 1,
    name: "Premium Chocolate Gift Box",
    slug: "premium-chocolate-gift-box",
    desc: "Assorted chocolates elegantly packed — perfect for gifting.",
    rating: 4.9,
    reviews: 220,
    img: "/giftbox-1.png",
    priceWas: 49.99,
    priceNow: 39.99,
  },
  {
    id: 2,
    name: "Luxury Spa Gift Box",
    slug: "luxury-spa-gift-box",
    desc: "Relaxing spa essentials curated for a perfect pampering session.",
    rating: 4.8,
    reviews: 180,
    img: "/giftbox-2.png",
    priceWas: 79.99,
    priceNow: 64.99,
  },
  {
    id: 3,
    name: "Gourmet Snack Gift Box",
    slug: "gourmet-snack-gift-box",
    desc: "A delightful mix of savory and sweet snacks for any occasion.",
    rating: 4.7,
    reviews: 150,
    img: "/giftbox-3.png",
    priceWas: 44.99,
    priceNow: 34.99,
  },
  {
    id: 4,
    name: "Corporate Appreciation Gift Box",
    slug: "corporate-appreciation-gift-box",
    desc: "Perfectly curated gifts to appreciate your employees or clients.",
    rating: 4.8,
    reviews: 200,
    img: "/giftbox-4.png",
    priceWas: 99.99,
    priceNow: 84.99,
  },
  {
    id: 5,
    name: "Festive Celebration Gift Box",
    slug: "festive-celebration-gift-box",
    desc: "Bright and cheerful gifts for holiday celebrations.",
    rating: 4.9,
    reviews: 250,
    img: "/giftbox-5.png",
    priceWas: 59.99,
    priceNow: 49.99,
  },
  {
    id: 6,
    name: "Deluxe Chocolate Gift Box",
    slug: "deluxe-chocolate-gift-box",
    desc: "Assorted chocolates elegantly packed — perfect for gifting.",
    rating: 4.9,
    reviews: 210,
    img: "/giftbox-1.png",
    priceWas: 54.99,
    priceNow: 44.99,
  },
  {
    id: 7,
    name: "Relaxing Spa Gift Box",
    slug: "relaxing-spa-gift-box",
    desc: "Spa essentials curated for relaxation and comfort.",
    rating: 4.8,
    reviews: 175,
    img: "/giftbox-2.png",
    priceWas: 74.99,
    priceNow: 59.99,
  },
  {
    id: 8,
    name: "Gourmet Snack Box",
    slug: "gourmet-snack-box",
    desc: "A curated mix of savory and sweet snacks for gifting.",
    rating: 4.7,
    reviews: 160,
    img: "/giftbox-3.png",
    priceWas: 39.99,
    priceNow: 29.99,
  },
  {
    id: 9,
    name: "Corporate Gift Set",
    slug: "corporate-gift-set",
    desc: "Premium corporate gifts to impress your clients or employees.",
    rating: 4.8,
    reviews: 190,
    img: "/giftbox-4.png",
    priceWas: 119.99,
    priceNow: 99.99,
  },
  {
    id: 10,
    name: "Festive Gift Set",
    slug: "festive-gift-set",
    desc: "Joyful gifts for festive celebrations and holidays.",
    rating: 4.9,
    reviews: 230,
    img: "/giftbox-5.png",
    priceWas: 64.99,
    priceNow: 54.99,
  },
  {
    id: 11,
    name: "Artisan Chocolate Gift Box",
    slug: "artisan-chocolate-gift-box",
    desc: "Handcrafted chocolates in an elegant gift box.",
    rating: 4.9,
    reviews: 200,
    img: "/giftbox-1.png",
    priceWas: 52.99,
    priceNow: 42.99,
  },
  {
    id: 12,
    name: "Premium Spa Gift Box",
    slug: "premium-spa-gift-box",
    desc: "Luxury spa essentials for a relaxing gifting experience.",
    rating: 4.8,
    reviews: 185,
    img: "/giftbox-2.png",
    priceWas: 89.99,
    priceNow: 74.99,
  },
];
