export const halfSleeve = [
  {
    id: 1,
    name: "Classic White Tee",
    slug: "classic-white-tee",
    desc: "Soft cotton t-shirt with a timeless fit — perfect for every occasion.",
    rating: 4.9,
    reviews: 1523,
    price: 19.99,
    img: "/tshirt-img1.png",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: 2,
    name: "Black Crew Neck",
    slug: "black-crew-neck",
    desc: "Sleek black crew neck t-shirt, versatile and comfortable.",
    rating: 4.8,
    reviews: 1345,
    price: 21.99,
    img: "/tshirt-img2.png",
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: 3,
    name: "Striped Tee",
    slug: "striped-tee",
    desc: "Casual striped t-shirt that adds style to everyday wear.",
    rating: 4.7,
    reviews: 1120,
    price: 24.99,
    img: "/tshirt-img3.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 4,
    name: "V-Neck Tee",
    slug: "v-neck-tee",
    desc: "Lightweight v-neck t-shirt for a relaxed yet polished look.",
    rating: 4.8,
    reviews: 980,
    price: 22.99,
    img: "/tshirt-img4.png",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 5,
    name: "Graphic Print Tee",
    slug: "graphic-print-tee",
    desc: "Trendy graphic print t-shirt to express your personality.",
    rating: 4.7,
    reviews: 860,
    price: 29.99,
    img: "/tshirt-img5.png",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 6,
    name: "Longline Tee",
    slug: "longline-tee",
    desc: "Extended length t-shirt for a modern streetwear vibe.",
    rating: 4.6,
    reviews: 740,
    price: 34.99,
    img: "/tshirt-img6.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 7,
    name: "Organic Cotton Tee",
    slug: "organic-cotton-tee",
    desc: "Eco-friendly organic cotton t-shirt — soft and sustainable.",
    rating: 4.9,
    reviews: 620,
    price: 25.99,
    img: "/tshirt-img7.png",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: 8,
    name: "Pocket Tee",
    slug: "pocket-tee",
    desc: "Casual t-shirt with a small chest pocket for style and function.",
    rating: 4.7,
    reviews: 540,
    price: 23.99,
    img: "/tshirt-img8.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 9,
    name: "Athletic Fit Tee",
    slug: "athletic-fit-tee",
    desc: "Tailored t-shirt with a sporty cut — ideal for workouts.",
    rating: 4.8,
    reviews: 410,
    price: 27.99,
    img: "/tshirt-img9.png",
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: 10,
    name: "Henley Tee",
    slug: "henley-tee",
    desc: "Classic henley t-shirt with buttoned placket for a rugged style.",
    rating: 4.6,
    reviews: 380,
    price: 32.99,
    img: "/tshirt-img10.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 11,
    name: "Ringer Tee",
    slug: "ringer-tee",
    desc: "Retro-inspired t-shirt with contrast collar and sleeve edges.",
    rating: 4.7,
    reviews: 355,
    price: 24.99,
    img: "/tshirt-img11.png",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 12,
    name: "Pocket Stripe Tee",
    slug: "pocket-stripe-tee",
    desc: "Striped t-shirt with chest pocket detail for casual flair.",
    rating: 4.8,
    reviews: 330,
    price: 26.99,
    img: "/tshirt-img12.png",
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: 13,
    name: "Sleeveless Tee",
    slug: "sleeveless-tee",
    desc: "Cool and breathable sleeveless t-shirt for summer days.",
    rating: 4.6,
    reviews: 305,
    price: 19.99,
    img: "/tshirt-img13.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 14,
    name: "Tie-Dye Tee",
    slug: "tie-dye-tee",
    desc: "Colorful tie-dye t-shirt for a fun, laid-back look.",
    rating: 4.9,
    reviews: 290,
    price: 34.99,
    img: "/tshirt-img14.png",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 15,
    name: "Soft Modal Tee",
    slug: "soft-modal-tee",
    desc: "Premium modal fabric t-shirt — silky smooth and light.",
    rating: 4.8,
    reviews: 275,
    price: 36.99,
    img: "/tshirt-img15.png",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 16,
    name: "Oversized Tee",
    slug: "oversized-tee",
    desc: "Relaxed oversized t-shirt for comfort and street style vibes.",
    rating: 4.7,
    reviews: 260,
    price: 29.99,
    img: "/tshirt-img16.png",
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
];
