export const hoodie = [
  {
    id: 1,
    name: "Classic White Hoodie",
    slug: "classic-white-hoodie",
    desc: "Soft cotton hoodie with a timeless fit — perfect for every occasion.",
    rating: 4.9,
    reviews: 1523,
    img: "/t-shirt4.png",
  },
  {
    id: 2,
    name: "Black Crew Neck Hoodie",
    slug: "black-crew-neck-hoodie",
    desc: "Sleek black hoodie, versatile and comfortable.",
    rating: 4.8,
    reviews: 1345,
    img: "/t-shirt4.png",
  },
  {
    id: 3,
    name: "Striped Hoodie",
    slug: "striped-hoodie",
    desc: "Casual striped hoodie that adds style to everyday wear.",
    rating: 4.7,
    reviews: 1120,
    img: "/t-shirt4.png",
  },
  {
    id: 4,
    name: "Graphic Print Hoodie",
    slug: "graphic-print-hoodie",
    desc: "Trendy graphic print hoodie to express your personality.",
    rating: 4.8,
    reviews: 980,
    img: "/t-shirt4.png",
  },
  {
    id: 5,
    name: "Longline Hoodie",
    slug: "longline-hoodie",
    desc: "Extended length hoodie for a modern streetwear vibe.",
    rating: 4.7,
    reviews: 860,
    img: "/t-shirt4.png",
  },
  {
    id: 6,
    name: "Organic Cotton Hoodie",
    slug: "organic-cotton-hoodie",
    desc: "Eco-friendly organic cotton hoodie — soft and sustainable.",
    rating: 4.6,
    reviews: 740,
    img: "/t-shirt4.png",
  },
  {
    id: 7,
    name: "Pocket Hoodie",
    slug: "pocket-hoodie",
    desc: "Casual hoodie with a small chest pocket for style and function.",
    rating: 4.9,
    reviews: 620,
    img: "/t-shirt4.png",
  },
  {
    id: 8,
    name: "Athletic Fit Hoodie",
    slug: "athletic-fit-hoodie",
    desc: "Tailored hoodie with a sporty cut — ideal for workouts.",
    rating: 4.7,
    reviews: 540,
    img: "/t-shirt4.png",
  },
  {
    id: 9,
    name: "Henley Hoodie",
    slug: "henley-hoodie",
    desc: "Classic henley style hoodie with buttoned placket.",
    rating: 4.8,
    reviews: 410,
    img: "/t-shirt4.png",
  },
  {
    id: 10,
    name: "Ringer Hoodie",
    slug: "ringer-hoodie",
    desc: "Retro-inspired hoodie with contrast collar and sleeve edges.",
    rating: 4.6,
    reviews: 380,
    img: "/t-shirt4.png",
  },
  {
    id: 11,
    name: "Pocket Stripe Hoodie",
    slug: "pocket-stripe-hoodie",
    desc: "Striped hoodie with chest pocket detail for casual flair.",
    rating: 4.7,
    reviews: 355,
    img: "/t-shirt4.png",
  },
  {
    id: 12,
    name: "Sleeveless Hoodie",
    slug: "sleeveless-hoodie",
    desc: "Cool and breathable hoodie for layering or summer wear.",
    rating: 4.8,
    reviews: 330,
    img: "/t-shirt4.png",
  },
  {
    id: 13,
    name: "Tie-Dye Hoodie",
    slug: "tie-dye-hoodie",
    desc: "Colorful tie-dye hoodie for a fun, laid-back look.",
    rating: 4.6,
    reviews: 305,
    img: "/t-shirt4.png",
  },
  {
    id: 14,
    name: "Soft Modal Hoodie",
    slug: "soft-modal-hoodie",
    desc: "Premium modal fabric hoodie — silky smooth and light.",
    rating: 4.9,
    reviews: 290,
    img: "/t-shirt4.png",
  },
  {
    id: 15,
    name: "Oversized Hoodie",
    slug: "oversized-hoodie",
    desc: "Relaxed oversized hoodie for comfort and street style vibes.",
    rating: 4.8,
    reviews: 275,
    img: "/t-shirt4.png",
  },
  {
    id: 16,
    name: "Graphic Oversized Hoodie",
    slug: "graphic-oversized-hoodie",
    desc: "Trendy oversized hoodie with modern graphic designs.",
    rating: 4.7,
    reviews: 260,
    img: "/t-shirt4.png",
  },
];
