export const packagingPro = [
  {
    id: 1,
    name: "Packaging Product 1",
    slug: "packaging-product-1",
    img: "/packaging-img1.png",
    rating: 4.8,
    reviews: 142,
    price: 29.99,
    desc: "Durable packaging designed to protect products and enhance brand presentation.",
  },
  {
    id: 2,
    name: "Packaging Product 2",
    slug: "packaging-product-2",
    img: "/packaging-img2.png",
    rating: 4.7,
    reviews: 89,
    price: 29.99,
    desc: "High-quality packaging ideal for retail items and promotional products.",
  },
  {
    id: 3,
    name: "Packaging Product 3",
    slug: "packaging-product-3",
    img: "/packaging-img3.png",
    rating: 4.9,
    reviews: 215,
    price: 29.99,
    desc: "Premium material packaging built to maintain product freshness and safety.",
  },
  {
    id: 4,
    name: "Packaging Product 4",
    slug: "packaging-product-4",
    img: "/packaging-img4.png",
    rating: 4.7,
    reviews: 110,
    price: 29.99,
    desc: "Customizable packaging perfect for brand identity and visual appeal.",
  },
  {
    id: 5,
    name: "Packaging Product 5",
    slug: "packaging-product-5",
    img: "/packaging-img5.png",
    rating: 4.8,
    reviews: 304,
    price: 29.99,
    desc: "Strong and stylish packaging suitable for corporate, retail, and gift items.",
  },
  {
    id: 6,
    name: "Packaging Product 6",
    slug: "packaging-product-6",
    img: "/packaging-img1.png",
    rating: 4.6,
    reviews: 76,
    price: 29.99,
    desc: "Durable and lightweight packaging for everyday business use.",
  },
  {
    id: 7,
    name: "Packaging Product 7",
    slug: "packaging-product-7",
    img: "/packaging-img2.png",
    rating: 4.7,
    reviews: 198,
    price: 29.99,
    desc: "Eco-friendly packaging solution with premium finishing options.",
  },
  {
    id: 8,
    name: "Packaging Product 8",
    slug: "packaging-product-8",
    img: "/packaging-img3.png",
    rating: 4.8,
    reviews: 234,
    price: 29.99,
    desc: "Versatile packaging perfect for food, cosmetics, and retail products.",
  },
  {
    id: 9,
    name: "Packaging Product 9",
    slug: "packaging-product-9",
    img: "/packaging-img4.png",
    rating: 4.7,
    reviews: 112,
    price: 29.99,
    desc: "Attractive packaging crafted for brand promotion and safe delivery.",
  },
  {
    id: 10,
    name: "Packaging Product 10",
    slug: "packaging-product-10",
    img: "/packaging-img5.png",
    rating: 4.9,
    reviews: 288,
    price: 29.99,
    desc: "High-end packaging designed to elevate product presentation.",
  },
  {
    id: 11,
    name: "Packaging Product 11",
    slug: "packaging-product-11",
    img: "/packaging-img1.png",
    rating: 4.6,
    reviews: 95,
    price: 29.99,
    desc: "Reliable packaging solution suitable for various industries.",
  },
  {
    id: 12,
    name: "Packaging Product 12",
    slug: "packaging-product-12",
    img: "/packaging-img2.png",
    rating: 4.7,
    reviews: 156,
    price: 29.99,
    desc: "Custom-printed packaging perfect for showcasing your brand.",
  },
  {
    id: 13,
    name: "Packaging Product 13",
    slug: "packaging-product-13",
    img: "/packaging-img3.png",
    rating: 4.8,
    reviews: 210,
    price: 29.99,
    desc: "High-quality packaging offering protection and premium appearance.",
  },
  {
    id: 14,
    name: "Packaging Product 14",
    slug: "packaging-product-14",
    img: "/packaging-img4.png",
    rating: 4.7,
    reviews: 145,
    price: 29.99,
    desc: "Unique packaging solution designed to enhance customer experience.",
  },
  {
    id: 15,
    name: "Packaging Product 15",
    slug: "packaging-product-15",
    img: "/packaging-img5.png",
    rating: 4.9,
    reviews: 325,
    price: 29.99,
    desc: "Luxury-grade packaging that gives your products a professional finish.",
  },
  {
    id: 16,
    name: "Packaging Product 16",
    slug: "packaging-product-16",
    img: "/packaging-img1.png",
    rating: 4.7,
    reviews: 134,
    price: 29.99,
    desc: "Versatile packaging suitable for e-commerce, retail, and gifts.",
  },
];
