// pensNotebooks.js
export const pens = [
  {
    id: 1,
    name: "Executive Metal Pen",
    slug: "executive-metal-pen",
    desc: "Smooth writing with premium metal finish.",
    rating: 4.8,
    reviews: 210,
    img: "/pens-1.png",
    priceWas: 24.99,
    priceNow: 19.99,
  },
  {
    id: 2,
    name: "Classic Gel Pen",
    slug: "classic-gel-pen",
    desc: "Vibrant ink flow for effortless writing experience.",
    rating: 4.7,
    reviews: 190,
    img: "/pens-2.png",
    priceWas: 14.99,
    priceNow: 11.99,
  },
  {
    id: 3,
    name: "Stylish Rollerball Pen",
    slug: "stylish-rollerball-pen",
    desc: "Professional design with smooth rollerball tip.",
    rating: 4.8,
    reviews: 180,
    img: "/pens-3.png",
    priceWas: 19.99,
    priceNow: 15.99,
  },
  {
    id: 4,
    name: "Eco-Friendly Bamboo Pen",
    slug: "eco-friendly-bamboo-pen",
    desc: "Sustainable bamboo pen for eco-conscious professionals.",
    rating: 4.7,
    reviews: 160,
    img: "/pens-5.png",
    priceWas: 17.99,
    priceNow: 13.99,
  },
  {
    id: 5,
    name: "Luxury Fountain Pen",
    slug: "luxury-fountain-pen",
    desc: "Elegant writing instrument for special occasions.",
    rating: 4.9,
    reviews: 150,
    img: "/pens-1.png",
    priceWas: 49.99,
    priceNow: 39.99,
  },
  {
    id: 6,
    name: "Pocket Pen Set",
    slug: "pocket-pen-set",
    desc: "Compact set of high-quality pens for everyday use.",
    rating: 4.8,
    reviews: 140,
    img: "/pens-2.png",
    priceWas: 29.99,
    priceNow: 24.99,
  },
  {
    id: 7,
    name: "Customizable Pen",
    slug: "customizable-pen",
    desc: "Personalize your pen with names or company logo.",
    rating: 4.9,
    reviews: 130,
    img: "/pens-3.png",
    priceWas: 22.99,
    priceNow: 17.99,
  },
  {
    id: 8,
    name: "Premium Ballpoint Pen",
    slug: "premium-ballpoint-pen",
    desc: "Classic design with smooth ink and long-lasting durability.",
    rating: 4.7,
    reviews: 120,
    img: "/pens-5.png",
    priceWas: 16.99,
    priceNow: 12.99,
  },
  {
    id: 9,
    name: "Stylish Notebook & Pen Combo",
    slug: "stylish-notebook-pen-combo",
    desc: "Perfect combo for corporate gifting and personal use.",
    rating: 4.8,
    reviews: 110,
    img: "/pens-1.png",
    priceWas: 34.99,
    priceNow: 27.99,
  },
  {
    id: 10,
    name: "Pocket Gel Pen",
    slug: "pocket-gel-pen",
    desc: "Compact, smooth gel pen for daily writing.",
    rating: 4.7,
    reviews: 100,
    img: "/pens-2.png",
    priceWas: 12.99,
    priceNow: 9.99,
  },
  {
    id: 11,
    name: "Luxury Notebook Pen Set",
    slug: "luxury-notebook-pen-set",
    desc: "Notebook and pen set with premium finishing.",
    rating: 4.9,
    reviews: 90,
    img: "/pens-3.png",
    priceWas: 54.99,
    priceNow: 44.99,
  },
  {
    id: 12,
    name: "Classic Ink Pen",
    slug: "classic-ink-pen",
    desc: "Reliable ink flow with elegant and timeless design.",
    rating: 4.8,
    reviews: 85,
    img: "/pens-5.png",
    priceWas: 18.99,
    priceNow: 14.99,
  },
];
