export const polloCollar = [
  {
    id: 1,
    name: "Classic White Pollo Collar",
    slug: "classic-white-pollo-collar",
    desc: "Soft cotton polo t-shirt with a timeless fit — perfect for every occasion.",
    rating: 4.9,
    reviews: 1523,
    img: "/t-shirt3.png",
  },
  {
    id: 2,
    name: "Black Crew Neck Pollo Collar",
    slug: "black-crew-neck-pollo-collar",
    desc: "Sleek black polo t-shirt, versatile and comfortable.",
    rating: 4.8,
    reviews: 1345,
    img: "/t-shirt3.png",
  },
  {
    id: 3,
    name: "Striped Pollo Collar",
    slug: "striped-pollo-collar",
    desc: "Casual striped polo t-shirt that adds style to everyday wear.",
    rating: 4.7,
    reviews: 1120,
    img: "/t-shirt3.png",
  },
  {
    id: 4,
    name: "Graphic Print Pollo Collar",
    slug: "graphic-print-pollo-collar",
    desc: "Trendy graphic print polo t-shirt to express your personality.",
    rating: 4.8,
    reviews: 980,
    img: "/t-shirt3.png",
  },
  {
    id: 5,
    name: "Longline Pollo Collar",
    slug: "longline-pollo-collar",
    desc: "Extended length polo t-shirt for a modern streetwear vibe.",
    rating: 4.7,
    reviews: 860,
    img: "/t-shirt3.png",
  },
  {
    id: 6,
    name: "Organic Cotton Pollo Collar",
    slug: "organic-cotton-pollo-collar",
    desc: "Eco-friendly organic cotton polo t-shirt — soft and sustainable.",
    rating: 4.6,
    reviews: 740,
    img: "/t-shirt3.png",
  },
  {
    id: 7,
    name: "Pocket Pollo Collar",
    slug: "pocket-pollo-collar",
    desc: "Casual polo t-shirt with a small chest pocket for style and function.",
    rating: 4.9,
    reviews: 620,
    img: "/t-shirt3.png",
  },
  {
    id: 8,
    name: "Athletic Fit Pollo Collar",
    slug: "athletic-fit-pollo-collar",
    desc: "Tailored polo t-shirt with a sporty cut — ideal for workouts.",
    rating: 4.7,
    reviews: 540,
    img: "/t-shirt3.png",
  },
  {
    id: 9,
    name: "Henley Pollo Collar",
    slug: "henley-pollo-collar",
    desc: "Classic henley style polo t-shirt with buttoned placket.",
    rating: 4.8,
    reviews: 410,
    img: "/t-shirt3.png",
  },
  {
    id: 10,
    name: "Ringer Pollo Collar",
    slug: "ringer-pollo-collar",
    desc: "Retro-inspired polo t-shirt with contrast collar and sleeve edges.",
    rating: 4.6,
    reviews: 380,
    img: "/t-shirt3.png",
  },
  {
    id: 11,
    name: "Pocket Stripe Pollo Collar",
    slug: "pocket-stripe-pollo-collar",
    desc: "Striped polo t-shirt with chest pocket detail for casual flair.",
    rating: 4.7,
    reviews: 355,
    img: "/t-shirt3.png",
  },
  {
    id: 12,
    name: "Sleeveless Pollo Collar",
    slug: "sleeveless-pollo-collar",
    desc: "Cool and breathable polo t-shirt for layering or summer wear.",
    rating: 4.8,
    reviews: 330,
    img: "/t-shirt3.png",
  },
  {
    id: 13,
    name: "Tie-Dye Pollo Collar",
    slug: "tie-dye-pollo-collar",
    desc: "Colorful tie-dye polo t-shirt for a fun, laid-back look.",
    rating: 4.6,
    reviews: 305,
    img: "/t-shirt3.png",
  },
  {
    id: 14,
    name: "Soft Modal Pollo Collar",
    slug: "soft-modal-pollo-collar",
    desc: "Premium modal fabric polo t-shirt — silky smooth and light.",
    rating: 4.9,
    reviews: 290,
    img: "/t-shirt3.png",
  },
  {
    id: 15,
    name: "Oversized Pollo Collar",
    slug: "oversized-pollo-collar",
    desc: "Relaxed oversized polo t-shirt for comfort and street style vibes.",
    rating: 4.8,
    reviews: 275,
    img: "/t-shirt3.png",
  },
  {
    id: 16,
    name: "Graphic Oversized Pollo Collar",
    slug: "graphic-oversized-pollo-collar",
    desc: "Trendy oversized polo t-shirt with modern graphic designs.",
    rating: 4.7,
    reviews: 260,
    img: "/t-shirt3.png",
  },
];
