export const printyDaters = [
  {
    id: 1,
    name: "Daters 1 (4 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img1.png",
    price: 45.99,
    oldPrice: 48.99,
    rating: 4.6,
    slug: "daters-1-4-lines",
  },
  {
    id: 2,
    name: "Daters 2 (5 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img2.png",
    price: 48.29,
    oldPrice: 50.99,
    rating: 4.7,
    slug: "daters-2-5-lines",
  },
  {
    id: 3,
    name: "Daters 3 (6 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img3.png",
    price: 49.99,
    oldPrice: 52.99,
    rating: 4.7,
    slug: "daters-3-6-lines",
  },
  {
    id: 4,
    name: "Daters 4 (7 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img4.png",
    price: 51.99,
    oldPrice: 54.99,
    rating: 4.8,
    slug: "daters-4-7-lines",
  },
  {
    id: 5,
    name: "Daters 5 (8 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img1.png",
    price: 53.99,
    oldPrice: 56.99,
    rating: 4.8,
    slug: "daters-5-8-lines",
  },
  {
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    id: 6,
    name: "Daters 6 (9 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img2.png",
    price: 55.49,
    oldPrice: 58.49,
    rating: 4.9,
    slug: "daters-6-9-lines",
  },
  {
    id: 7,
    name: "Daters 7 (10 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img3.png",
    price: 57.99,
    oldPrice: 60.99,
    rating: 4.9,
    slug: "daters-7-10-lines",
  },
  {
    id: 8,
    name: "Daters 8 (11 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img1.png",
    price: 60.29,
    oldPrice: 63.29,
    rating: 4.8,
    slug: "daters-8-11-lines",
  },
  {
    id: 9,
    name: "Daters 9 (12 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img1.png",
    price: 62.99,
    oldPrice: 65.99,
    rating: 4.9,
    slug: "daters-9-12-lines",
  },
  {
    id: 10,
    name: "Daters 10 (13 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img2.png",
    price: 64.99,
    oldPrice: 68.0,
    rating: 4.9,
    slug: "daters-10-13-lines",
  },
  {
    id: 11,
    name: "Daters 11 (14 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img3.png",
    price: 67.49,
    oldPrice: 70.49,
    rating: 4.9,
    slug: "daters-11-14-lines",
  },
  {
    id: 12,
    name: "Daters 12 (15 lines)",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/Printystamp-img4.png",
    price: 69.99,
    oldPrice: 73.0,
    rating: 4.9,
    slug: "daters-12-15-lines",
  },
];
