export const products = [
  {
    id: 1,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-1.png",
    price: 49.99,
    reviews: 140,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black", "Grey"],
    slug: "printed-t-shirts-1",
    category: "apparel",
  },
  {
    id: 2,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-2.png",
    price: 59.99,
    reviews: 120,
    sizes: ["M", "L", "XL"],
    colors: ["Red", "White", "Black"],
    slug: "printed-t-shirts-2",
    category: "apparel",
  },
  {
    id: 3,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-3.png",
    price: 45.99,
    reviews: 90,
    sizes: ["S", "M", "L"],
    colors: ["Yellow", "Blue", "Green"],
    slug: "printed-t-shirts-3",
    category: "apparel",
  },
  {
    id: 4,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-4.png",
    price: 52.99,
    reviews: 150,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Grey", "White"],
    slug: "printed-t-shirts-4",
    category: "apparel",
  },
  {
    id: 5,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-5.png",
    price: 48.99,
    reviews: 110,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Red", "Navy"],
    slug: "printed-t-shirts-5",
    category: "apparel",
  },
  {
    id: 6,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-6.png",
    price: 55.99,
    reviews: 95,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Olive"],
    slug: "printed-t-shirts-6",
    category: "apparel",
  },
  {
    id: 7,
    name: "Printed T-Shirts",
    category: "apparel",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-7.png",
    price: 50.99,
    reviews: 130,
    sizes: ["M", "L", "XL"],
    colors: ["Grey", "Blue", "Brown"],
    slug: "printed-t-shirts-7",
  },
  {
    id: 8,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-8.png",
    price: 47.99,
    reviews: 80,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Yellow", "Black"],
    category: "apparel",
    slug: "printed-t-shirts-8",
  },
  {
    id: 9,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-9.png",
    price: 53.99,
    reviews: 100,
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Green", "White"],
    slug: "printed-t-shirts-9",
    category: "apparel",
  },
  {
    id: 10,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-10.png",
    price: 51.99,
    reviews: 115,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy"],
    slug: "printed-t-shirts-10",
    category: "apparel",
  },
  {
    id: 11,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-11.png",
    price: 54.99,
    reviews: 105,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue", "Black"],
    slug: "printed-t-shirts-11",
    category: "apparel",
  },
  {
    id: 12,
    name: "Printed T-Shirts",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/product-12.png",
    price: 49.49,
    reviews: 95,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Grey", "White", "Navy"],
    slug: "printed-t-shirts-12",
    category: "apparel",
  },
];
