export const promotional = [
  {
    id: 1,
    name: "Custom Mugs",
    slug: "custom-mugs",
    desc: "Personalized ceramic mugs ideal for corporate gifting and brand promotions.",
    rating: 4.9,
    reviews: 15200,
    img: "/promo-img1.png",
  },
  {
    id: 2,
    name: "Branded T-Shirts",
    slug: "branded-t-shirts",
    desc: "High-quality printed T-shirts perfect for events, marketing, and staff uniforms.",
    rating: 4.8,
    reviews: 14210,
    img: "/promo-img2.png",
  },
  {
    id: 3,
    name: "Keychains",
    slug: "keychains",
    desc: "Durable customized keychains ideal for giveaways and company branding.",
    rating: 4.7,
    reviews: 13140,
    img: "/promo-img3.png",
  },
  {
    id: 4,
    name: "Custom Pens",
    slug: "custom-pens",
    desc: "Smooth-writing branded pens perfect for office use and promotional gifting.",
    rating: 4.6,
    reviews: 12200,
    img: "/promo-img4.png",
  },
  {
    id: 5,
    name: "Corporate Diaries",
    slug: "corporate-diaries",
    desc: "Premium notebooks and diaries ideal for employees, meetings, and giveaways.",
    rating: 4.9,
    reviews: 11550,
    img: "/promo-img5.png",
  },
  {
    id: 6,
    name: "Tote Bags",
    slug: "tote-bags",
    desc: "Reusable printed tote bags ideal for events, stores, and eco-friendly branding.",
    rating: 4.7,
    reviews: 10780,
    img: "/promo-img1.png",
  },
  {
    id: 7,
    name: "Water Bottles",
    slug: "water-bottles",
    desc: "Durable branded bottles ideal for fitness events, offices, and gifting.",
    rating: 4.8,
    reviews: 9980,
    img: "/promo-img2.png",
  },
  {
    id: 8,
    name: "Desk Calendars",
    slug: "desk-calendars",
    desc: "Custom-designed calendars perfect for corporate distribution.",
    rating: 4.7,
    reviews: 9450,
    img: "/promo-img3.png",
  },
  {
    id: 9,
    name: "USB Flash Drives",
    slug: "usb-flash-drives",
    desc: "High-speed custom USB drives great for corporate giveaways.",
    rating: 4.8,
    reviews: 8890,
    img: "/promo-img4.png",
  },
  {
    id: 10,
    name: "Badges & Buttons",
    slug: "badges-buttons",
    desc: "Custom badges for events, campaigns, and branding.",
    rating: 4.7,
    reviews: 8350,
    img: "/promo-img5.png",
  },
  {
    id: 11,
    name: "Table Calendars",
    slug: "table-calendars",
    desc: "Compact promotional calendars ideal for office desks.",
    rating: 4.8,
    reviews: 7900,
    img: "/promo-img1.png",
  },
  {
    id: 12,
    name: "Mouse Pads",
    slug: "mouse-pads",
    desc: "High-quality printed mousepads suitable for giveaways and offices.",
    rating: 4.7,
    reviews: 7400,
    img: "/promo-img2.png",
  },
  {
    id: 13,
    name: "Stickers & Labels",
    slug: "stickers-labels",
    desc: "Custom stickers for packaging, branding, and promotions.",
    rating: 4.6,
    reviews: 6900,
    img: "/promo-img3.png",
  },
  {
    id: 14,
    name: "Gift Boxes",
    slug: "gift-boxes",
    desc: "Elegant branded gift boxes for corporate gifting and product packaging.",
    rating: 4.9,
    reviews: 6500,
    img: "/promo-img4.png",
  },
  {
    id: 15,
    name: "Lanyards",
    slug: "lanyards",
    desc: "Custom printed lanyards ideal for offices, schools, and events.",
    rating: 4.8,
    reviews: 6000,
    img: "/promo-img5.png",
  },
  {
    id: 16,
    name: "Desk Organizers",
    slug: "desk-organizers",
    desc: "Stylish custom organizers great for workplace branding and gifting.",
    rating: 4.7,
    reviews: 5600,
    img: "/promo-img1.png",
  },
];
