export const signsBanner = [
  {
    id: 1,
    name: "Vinyl Banners",
    slug: "vinyl-banners",
    desc: "Durable outdoor vinyl banners ideal for promotions, store displays, and events.",
    rating: 4.9,
    reviews: 15200,
    img: "/sign-img1.png",
  },
  {
    id: 2,
    name: "Roll-Up Stands",
    slug: "roll-up-stands",
    desc: "Portable pull-up stands perfect for exhibitions, trade shows, and presentations.",
    rating: 4.8,
    reviews: 13110,
    img: "/sign-img2.png",
  },
  {
    id: 3,
    name: "Foam Board Signs",
    slug: "foam-board-signs",
    desc: "Lightweight foam board signs great for indoor branding and event displays.",
    rating: 4.7,
    reviews: 11820,
    img: "/sign-img3.png",
  },
  {
    id: 4,
    name: "Acrylic Signs",
    slug: "acrylic-signs",
    desc: "Premium acrylic signage for reception areas and office branding.",
    rating: 4.6,
    reviews: 10450,
    img: "/sign-img4.png",
  },
  {
    id: 5,
    name: "Outdoor Hoardings",
    slug: "outdoor-hoardings",
    desc: "Large-format hoardings for outdoor advertising and long-term visibility.",
    rating: 4.9,
    reviews: 9800,
    img: "/sign-img5.png",
  },
  {
    id: 6,
    name: "Flag Banners",
    slug: "flag-banners",
    desc: "Promotional flag banners ideal for outdoor events, exhibitions, and sales.",
    rating: 4.7,
    reviews: 8600,
    img: "/sign-img1.png",
  },
  {
    id: 7,
    name: "Backlit Signs",
    slug: "backlit-signs",
    desc: "Illuminated backlit signage designed for maximum nighttime visibility.",
    rating: 4.8,
    reviews: 7900,
    img: "/sign-img2.png",
  },
  {
    id: 8,
    name: "Mesh Banners",
    slug: "mesh-banners",
    desc: "Wind-resistant mesh banners suitable for large outdoor installations.",
    rating: 4.7,
    reviews: 7420,
    img: "/sign-img3.png",
  },
  {
    id: 9,
    name: "X-Banners",
    slug: "x-banners",
    desc: "Cost-effective X-stand banners perfect for indoor promotional setups.",
    rating: 4.8,
    reviews: 6900,
    img: "/sign-img4.png",
  },
  {
    id: 10,
    name: "Poster Prints",
    slug: "poster-prints",
    desc: "High-quality posters for events, retail displays, and marketing campaigns.",
    rating: 4.7,
    reviews: 6400,
    img: "/sign-img5.png",
  },
  {
    id: 11,
    name: "Aluminum Signs",
    slug: "aluminum-signs",
    desc: "Strong and weather-resistant aluminum signs for outdoor usage.",
    rating: 4.8,
    reviews: 5800,
    img: "/sign-img1.png",
  },
  {
    id: 12,
    name: "Street Pole Banners",
    slug: "street-pole-banners",
    desc: "Double-sided banners mounted on poles for city-wide advertising.",
    rating: 4.7,
    reviews: 5200,
    img: "/sign-img2.png",
  },
  {
    id: 13,
    name: "Snap Frame Posters",
    slug: "snap-frame-posters",
    desc: "Easy-change snap frames ideal for restaurants, malls, and offices.",
    rating: 4.6,
    reviews: 4700,
    img: "/sign-img3.png",
  },
  {
    id: 14,
    name: "Canvas Prints",
    slug: "canvas-prints",
    desc: "Premium canvas prints for interior decoration and gallery displays.",
    rating: 4.9,
    reviews: 4300,
    img: "/sign-img4.png",
  },
  {
    id: 15,
    name: "Event Backdrops",
    slug: "event-backdrops",
    desc: "Large custom backdrops for corporate events, weddings, and ceremonies.",
    rating: 4.8,
    reviews: 4100,
    img: "/sign-img5.png",
  },
  {
    id: 16,
    name: "Show Backdrops",
    slug: "show-backdrops",
    desc: "Large custom backdrops for corporate events, weddings, and ceremonies.",
    rating: 4.9,
    reviews: 4500,
    img: "/sign-img1.png",
  },
];
