export const stickers = [
  {
    id: 1,
    name: "Sticker & Label 1",
    slug: "sticker-label-1",
    img: "/sticker-img1.png",
    rating: 4.7,
    reviews: 120,
    price: 29.99,
    desc: "High-quality custom stickers perfect for product labeling and branding.",
  },
  {
    id: 2,
    name: "Sticker & Label 2",
    slug: "sticker-label-2",
    img: "/sticker-img2.png",
    rating: 4.6,
    reviews: 85,
    price: 29.99,
    desc: "Durable and vibrant stickers ideal for packaging and brand promotion.",
  },
  {
    id: 3,
    name: "Sticker & Label 3",
    slug: "sticker-label-3",
    img: "/sticker-img3.png",
    rating: 4.8,
    reviews: 230,
    price: 29.99,
    desc: "Premium waterproof labels suitable for bottles, jars, and containers.",
  },
  {
    id: 4,
    name: "Sticker & Label 4",
    slug: "sticker-label-4",
    img: "/sticker-img4.png",
    rating: 4.7,
    reviews: 145,
    price: 29.99,
    desc: "Custom cut stickers available in multiple shapes and finishes.",
  },
  {
    id: 5,
    name: "Sticker & Label 5",
    slug: "sticker-label-5",
    img: "/sticker-img5.png",
    rating: 4.9,
    reviews: 310,
    price: 29.99,
    desc: "High-resolution print stickers ideal for branding and promotions.",
  },
  {
    id: 6,
    name: "Sticker & Label 6",
    slug: "sticker-label-6",
    img: "/sticker-img1.png",
    rating: 4.6,
    reviews: 95,
    price: 29.99,
    desc: "Strong adhesive labels suitable for all types of packaging.",
  },
  {
    id: 7,
    name: "Sticker & Label 7",
    slug: "sticker-label-7",
    img: "/sticker-img2.png",
    rating: 4.7,
    reviews: 175,
    price: 29.99,
    desc: "Vibrant and long-lasting stickers perfect for outdoor use.",
  },
  {
    id: 8,
    name: "Sticker & Label 8",
    slug: "sticker-label-8",
    img: "/sticker-img3.png",
    rating: 4.8,
    reviews: 210,
    price: 29.99,
    desc: "Waterproof custom labels ideal for product branding.",
  },
  {
    id: 9,
    name: "Sticker & Label 9",
    slug: "sticker-label-9",
    img: "/sticker-img4.png",
    rating: 4.7,
    reviews: 134,
    price: 29.99,
    desc: "Premium quality stickers with scratch-resistant coating.",
  },
  {
    id: 10,
    name: "Sticker & Label 10",
    slug: "sticker-label-10",
    img: "/sticker-img5.png",
    rating: 4.8,
    reviews: 256,
    price: 29.99,
    desc: "High-gloss and matte finish stickers for versatile applications.",
  },
  {
    id: 11,
    name: "Sticker & Label 11",
    slug: "sticker-label-11",
    img: "/sticker-img1.png",
    rating: 4.6,
    reviews: 112,
    price: 29.99,
    desc: "Customizable labels ideal for brand packaging and shipping.",
  },
  {
    id: 12,
    name: "Sticker & Label 12",
    slug: "sticker-label-12",
    img: "/sticker-img2.png",
    rating: 4.7,
    reviews: 189,
    price: 29.99,
    desc: "Premium stickers with excellent durability and color accuracy.",
  },
  {
    id: 13,
    name: "Sticker & Label 13",
    slug: "sticker-label-13",
    img: "/sticker-img3.png",
    rating: 4.8,
    reviews: 245,
    price: 29.99,
    desc: "Perfect for labeling jars, bottles, bags, and product boxes.",
  },
  {
    id: 14,
    name: "Sticker & Label 14",
    slug: "sticker-label-14",
    img: "/sticker-img4.png",
    rating: 4.7,
    reviews: 167,
    price: 29.99,
    desc: "Fade-resistant stickers ideal for long-term use.",
  },
  {
    id: 15,
    name: "Sticker & Label 15",
    slug: "sticker-label-15",
    img: "/sticker-img5.png",
    rating: 4.9,
    reviews: 342,
    price: 29.99,
    desc: "High-quality print labels to enhance product presentation.",
  },
  {
    id: 16,
    name: "Sticker & Label 16",
    slug: "sticker-label-16",
    img: "/sticker-img1.png",
    rating: 4.6,
    reviews: 128,
    price: 29.99,
    desc: "Durable stickers suitable for branding promotional items.",
  },
];
