export const stockstamps = [
  {
    id: 1,
    name: "SS 101 — PAID Stamp (1 x 2)",
    desc: "High-quality stock stamp ideal for quick office use.",
    img: "/Printystamp-img1.png",
    price: 9.99,
    oldPrice: 11.49,
    rating: 4.8,
    slug: "ss-101-paid-stamp-1-x-2",
  },
  {
    id: 2,
    name: "SS 102 — APPROVED Stamp (1 x 2)",
    desc: "Perfect for documents requiring instant approval marking.",
    img: "/Printystamp-img1.png",
    price: 10.49,
    oldPrice: 12.49,
    rating: 4.7,
    slug: "ss-102-approved-stamp-1-x-2",
  },
  {
    id: 3,
    name: "SS 103 — RECEIVED Stamp (1 x 2 1/4)",
    desc: "Clear and bold imprint for incoming documents.",
    img: "/Printystamp-img1.png",
    price: 10.99,
    oldPrice: 12.99,
    rating: 4.8,
    slug: "ss-103-received-stamp-1-x-2-1-4",
  },
  {
    id: 4,
    name: "SS 104 — URGENT Stamp (1 x 2 1/4)",
    desc: "Bright and noticeable marking for priority tasks.",
    img: "/Printystamp-img1.png",
    price: 11.49,
    oldPrice: 13.49,
    rating: 4.7,
    slug: "ss-104-urgent-stamp-1-x-2-1-4",
  },
  {
    id: 5,
    name: "SS 105 — COMPLETED Stamp (1 x 2 1/2)",
    desc: "Efficient for marking finished tasks and forms.",
    img: "/Printystamp-img1.png",
    price: 11.99,
    oldPrice: 13.99,
    rating: 4.9,
    slug: "ss-105-completed-stamp-1-x-2-1-2",
  },
  {
    id: 6,
    name: "SS 106 — CANCELLED Stamp (1 x 2 1/2)",
    desc: "Durable rubber stamp for bold cancellation marking.",
    img: "/Printystamp-img1.png",
    price: 12.49,
    oldPrice: 14.49,
    rating: 4.8,
    slug: "ss-106-cancelled-stamp-1-x-2-1-2",
  },
  {
    id: 7,
    name: "SS 107 — COPY Stamp (1 x 2 3/4)",
    desc: "Perfect for document duplication workflows.",
    img: "/Printystamp-img1.png",
    price: 12.99,
    oldPrice: 14.99,
    rating: 4.7,
    slug: "ss-107-copy-stamp-1-x-2-3-4",
  },
  {
    id: 8,
    name: "SS 108 — FAXED Stamp (1 x 2 3/4)",
    desc: "Designed for offices handling large fax volumes.",
    img: "/Printystamp-img1.png",
    price: 13.49,
    oldPrice: 15.49,
    rating: 4.8,
    slug: "ss-108-faxed-stamp-1-x-2-3-4",
  },
  {
    id: 9,
    name: "SS 109 — VOID Stamp (1 x 3)",
    desc: "Creates clean and highly visible VOID impressions.",
    img: "/Printystamp-img1.png",
    price: 13.99,
    oldPrice: 15.99,
    rating: 4.9,
    slug: "ss-109-void-stamp-1-x-3",
  },
  {
    id: 10,
    name: "SS 110 — CONFIDENTIAL Stamp (1 1/4 x 3)",
    desc: "Ideal for securing sensitive or private documents.",
    img: "/Printystamp-img1.png",
    price: 14.49,
    oldPrice: 16.49,
    rating: 5.0,
    slug: "ss-110-confidential-stamp-1-1-4-x-3",
  },
  {
    id: 11,
    name: "SS 111 — IMPORTANT Stamp (1 1/4 x 3)",
    desc: "Perfect for highlighting important documents and files.",
    img: "/Printystamp-img1.png",
    price: 14.99,
    oldPrice: 16.99,
    rating: 4.9,
    slug: "ss-111-important-stamp-1-1-4-x-3",
  },
  {
    id: 12,
    name: "SS 112 — DRAFT Stamp (1 1/4 x 3)",
    desc: "Ideal for marking documents that are in progress.",
    img: "/Printystamp-img1.png",
    price: 15.49,
    oldPrice: 17.49,
    rating: 4.8,
    slug: "ss-112-draft-stamp-1-1-4-x-3",
  },
  {
    id: 13,
    name: "SS 113 — ORIGINAL Stamp (1 1/4 x 3 1/4)",
    desc: "Ensures clear identification of original paperwork.",
    img: "/Printystamp-img1.png",
    price: 15.99,
    oldPrice: 17.99,
    rating: 4.9,
    slug: "ss-113-original-stamp-1-1-4-x-3-1-4",
  },
  {
    id: 14,
    name: "SS 114 — FILED Stamp (1 1/4 x 3 1/4)",
    desc: "Great for organizing documents quickly and efficiently.",
    img: "/Printystamp-img1.png",
    price: 16.49,
    oldPrice: 18.49,
    rating: 5.0,
    slug: "ss-114-filed-stamp-1-1-4-x-3-1-4",
  },
];
