// techGifts.js
export const tech = [
  {
    id: 1,
    name: "Wireless Bluetooth Earbuds",
    slug: "wireless-bluetooth-earbuds",
    desc: "High-quality sound and compact design for on-the-go listening.",
    rating: 4.9,
    reviews: 320,
    img: "/tech-1.png",
    priceWas: 69.99,
    priceNow: 54.99,
  },
  {
    id: 2,
    name: "Portable Power Bank",
    slug: "portable-power-bank",
    desc: "Charge your devices anywhere with this high-capacity power bank.",
    rating: 4.8,
    reviews: 280,
    img: "/tech-2.png",
    priceWas: 49.99,
    priceNow: 39.99,
  },
  {
    id: 3,
    name: "Smart Fitness Tracker",
    slug: "smart-fitness-tracker",
    desc: "Monitor your health and activity with style and precision.",
    rating: 4.7,
    reviews: 250,
    img: "/tech-3.png",
    priceWas: 89.99,
    priceNow: 74.99,
  },
  {
    id: 4,
    name: "USB-C Multiport Hub",
    slug: "usb-c-multiport-hub",
    desc: "Expand your laptop connectivity with this sleek multiport hub.",
    rating: 4.8,
    reviews: 220,
    img: "/tech-1.png",
    priceWas: 44.99,
    priceNow: 34.99,
  },
  {
    id: 5,
    name: "Wireless Charging Pad",
    slug: "wireless-charging-pad",
    desc: "Fast wireless charging for smartphones and other devices.",
    rating: 4.9,
    reviews: 310,
    img: "/tech-2.png",
    priceWas: 39.99,
    priceNow: 29.99,
  },
  {
    id: 6,
    name: "Noise Cancelling Headphones",
    slug: "noise-cancelling-headphones",
    desc: "Immersive sound experience with superior noise cancellation.",
    rating: 4.8,
    reviews: 290,
    img: "/tech-3.png",
    priceWas: 119.99,
    priceNow: 99.99,
  },
  {
    id: 7,
    name: "Smart LED Desk Lamp",
    slug: "smart-led-desk-lamp",
    desc: "Adjustable brightness and color for optimal workspace lighting.",
    rating: 4.7,
    reviews: 230,
    img: "/tech-1.png",
    priceWas: 54.99,
    priceNow: 44.99,
  },
  {
    id: 8,
    name: "Mini Bluetooth Speaker",
    slug: "mini-bluetooth-speaker",
    desc: "Compact speaker with powerful sound and long battery life.",
    rating: 4.8,
    reviews: 210,
    img: "/tech-2.png",
    priceWas: 59.99,
    priceNow: 47.99,
  },
  {
    id: 9,
    name: "Smart Plug",
    slug: "smart-plug",
    desc: "Control your devices remotely with this easy-to-use smart plug.",
    rating: 4.7,
    reviews: 200,
    img: "/tech-3.png",
    priceWas: 29.99,
    priceNow: 22.99,
  },
  {
    id: 10,
    name: "Wireless Mouse",
    slug: "wireless-mouse",
    desc: "Ergonomic design with precision tracking for comfort and efficiency.",
    rating: 4.8,
    reviews: 190,
    img: "/tech-1.png",
    priceWas: 34.99,
    priceNow: 27.99,
  },
  {
    id: 11,
    name: "Portable Mini Projector",
    slug: "portable-mini-projector",
    desc: "Enjoy movies and presentations anywhere with this compact projector.",
    rating: 4.7,
    reviews: 180,
    img: "/tech-2.png",
    priceWas: 149.99,
    priceNow: 124.99,
  },
  {
    id: 12,
    name: "Bluetooth Key Finder",
    slug: "bluetooth-key-finder",
    desc: "Never lose your keys or accessories with this smart tracker.",
    rating: 4.9,
    reviews: 170,
    img: "/tech-3.png",
    priceWas: 24.99,
    priceNow: 19.99,
  },
];
