export const vNeck = [
  {
    id: 1,
    name: "Classic White V-Neck",
    slug: "classic-white-v-neck",
    desc: "Soft cotton v-neck t-shirt with a timeless fit — perfect for every occasion.",
    rating: 4.9,
    reviews: 1523,
    img: "/t-shirt5.png",
  },
  {
    id: 2,
    name: "Black Crew Neck V-Neck",
    slug: "black-crew-neck-v-neck",
    desc: "Sleek black v-neck t-shirt, versatile and comfortable.",
    rating: 4.8,
    reviews: 1345,
    img: "/t-shirt5.png",
  },
  {
    id: 3,
    name: "Striped V-Neck",
    slug: "striped-v-neck",
    desc: "Casual striped v-neck t-shirt that adds style to everyday wear.",
    rating: 4.7,
    reviews: 1120,
    img: "/t-shirt5.png",
  },
  {
    id: 4,
    name: "Graphic Print V-Neck",
    slug: "graphic-print-v-neck",
    desc: "Trendy graphic print v-neck t-shirt to express your personality.",
    rating: 4.8,
    reviews: 980,
    img: "/t-shirt5.png",
  },
  {
    id: 5,
    name: "Longline V-Neck",
    slug: "longline-v-neck",
    desc: "Extended length v-neck t-shirt for a modern streetwear vibe.",
    rating: 4.7,
    reviews: 860,
    img: "/t-shirt5.png",
  },
  {
    id: 6,
    name: "Organic Cotton V-Neck",
    slug: "organic-cotton-v-neck",
    desc: "Eco-friendly organic cotton v-neck t-shirt — soft and sustainable.",
    rating: 4.6,
    reviews: 740,
    img: "/t-shirt5.png",
  },
  {
    id: 7,
    name: "Pocket V-Neck",
    slug: "pocket-v-neck",
    desc: "Casual v-neck t-shirt with a small chest pocket for style and function.",
    rating: 4.9,
    reviews: 620,
    img: "/t-shirt5.png",
  },
  {
    id: 8,
    name: "Athletic Fit V-Neck",
    slug: "athletic-fit-v-neck",
    desc: "Tailored v-neck t-shirt with a sporty cut — ideal for workouts.",
    rating: 4.7,
    reviews: 540,
    img: "/t-shirt5.png",
  },
  {
    id: 9,
    name: "Henley V-Neck",
    slug: "henley-v-neck",
    desc: "Classic henley style v-neck t-shirt with buttoned placket.",
    rating: 4.8,
    reviews: 410,
    img: "/t-shirt5.png",
  },
  {
    id: 10,
    name: "Ringer V-Neck",
    slug: "ringer-v-neck",
    desc: "Retro-inspired v-neck t-shirt with contrast collar and sleeve edges.",
    rating: 4.6,
    reviews: 380,
    img: "/t-shirt5.png",
  },
  {
    id: 11,
    name: "Pocket Stripe V-Neck",
    slug: "pocket-stripe-v-neck",
    desc: "Striped v-neck t-shirt with chest pocket detail for casual flair.",
    rating: 4.7,
    reviews: 355,
    img: "/t-shirt5.png",
  },
  {
    id: 12,
    name: "Sleeveless V-Neck",
    slug: "sleeveless-v-neck",
    desc: "Cool and breathable v-neck t-shirt for layering or summer wear.",
    rating: 4.8,
    reviews: 330,
    img: "/t-shirt5.png",
  },
  {
    id: 13,
    name: "Tie-Dye V-Neck",
    slug: "tie-dye-v-neck",
    desc: "Colorful tie-dye v-neck t-shirt for a fun, laid-back look.",
    rating: 4.6,
    reviews: 305,
    img: "/t-shirt5.png",
  },
  {
    id: 14,
    name: "Soft Modal V-Neck",
    slug: "soft-modal-v-neck",
    desc: "Premium modal fabric v-neck t-shirt — silky smooth and light.",
    rating: 4.9,
    reviews: 290,
    img: "/t-shirt5.png",
  },
  {
    id: 15,
    name: "Oversized V-Neck",
    slug: "oversized-v-neck",
    desc: "Relaxed oversized v-neck t-shirt for comfort and street style vibes.",
    rating: 4.8,
    reviews: 275,
    img: "/t-shirt5.png",
  },
  {
    id: 16,
    name: "Graphic Oversized V-Neck",
    slug: "graphic-oversized-v-neck",
    desc: "Trendy oversized v-neck t-shirt with modern graphic designs.",
    rating: 4.7,
    reviews: 260,
    img: "/t-shirt5.png",
  },
];
