export const businessCards = [
  {
    id: 1,
    name: "Standard Business Cards",
    desc: "Lorem Ipsum is simply dummy text of the printing.",
    img: "/businesscards-img1.png",
    price: 49.99,
    reviews: 140,
    slug: "standard-business-cards",
    category: "digital printing",
  },
  {
    id: 2,
    name: "Premium Business Card",
    desc: "High-quality business cards for your brand or personal use.",
    img: "/businesscards-img2.png",
    price: 29.99,
    reviews: 95,
    slug: "premium-business-card",
    category: "digital printing",
  },
  {
    id: 3,
    name: "Textured Business Cards",
    desc: "Durable stickers to showcase your logo or design.",
    img: "/businesscards-img3.png",
    price: 19.99,
    reviews: 80,
    slug: "textured-business-cards",
    category: "digital printing",
  },
  {
    id: 4,
    name: "Embossed / Debossed Cards",
    desc: "Personalized notebooks for office or personal use.",
    img: "/businesscards-img4.png",
    price: 24.99,
    reviews: 65,
    slug: "embossed-debossed-cards",
    category: "digital printing",
  },
  {
    id: 5,
    name: "Spot UV Cards",
    desc: "Sleek pens with your brand logo printed.",
    img: "/businesscards-img5.png",
    price: 9.99,
    reviews: 120,
    slug: "spot-uv-cards",
    category: "digital printing",
  },
];
