export const cardPrintAds = [
  {
    id: 1,
    name: "Flyers & Leaflets",
    desc: "High-quality flyers and leaflets to promote your business effectively.",
    img: "/card-img1.png",
    price: 39.99,
    reviews: 85,
    slug: "flyers-leaflets",
    category: "print advertising",
  },
  {
    id: 2,
    name: "Posters & Banners",
    desc: "Large format posters and banners for events, promotions, and displays.",
    img: "card-img2.png",
    price: 59.99,
    reviews: 70,
    slug: "posters-banners",
    category: "print advertising",
  },
  {
    id: 3,
    name: "Brochures",
    desc: "Professionally designed brochures to showcase your products and services.",
    img: "/card-img3.png",
    price: 49.99,
    reviews: 90,
    slug: "brochures",
    category: "print advertising",
  },
  {
    id: 4,
    name: "Catalogues",
    desc: "Detailed product catalogues for your customers with a professional touch.",
    img: "/card-img4.png",
    price: 69.99,
    reviews: 60,
    slug: "catalogues",
    category: "print advertising",
  },
  {
    id: 5,
    name: "Menu Cards",
    desc: "Custom printed menu cards for restaurants and cafes.",
    img: "/card-img5.png",
    price: 29.99,
    reviews: 100,
    slug: "menu-cards",
    category: "print advertising",
  },
];
