export const packaging = [
  {
    id: 1,
    name: "Custom Boxes",
    desc: "Durable and stylish custom boxes for your products and gifts.",
    img: "/packaging-img1.png",
    price: 29.99,
    reviews: 120,
    slug: "custom-boxes",
    category: "packaging",
  },
  {
    id: 2,
    name: "Gift Packaging",
    desc: "Premium gift packaging solutions for special occasions.",
    img: "/packaging-img2.png",
    price: 19.99,
    reviews: 95,
    slug: "gift-packaging",
    category: "packaging",
  },
  {
    id: 3,
    name: "Food Packaging",
    desc: "Safe and durable food packaging for restaurants and delivery.",
    img: "/packaging-img3.png",
    price: 24.99,
    reviews: 110,
    slug: "food-packaging",
    category: "packaging",
  },
  {
    id: 4,
    name: "Bottle & Jar Packaging",
    desc: "Custom packaging solutions for bottles and jars.",
    img: "/packaging-img4.png",
    price: 34.99,
    reviews: 85,
    slug: "bottle-jar-packaging",
    category: "packaging",
  },
  {
    id: 5,
    name: "Eco-Friendly Packaging",
    desc: "Sustainable and eco-friendly packaging options for products.",
    img: "/packaging-img5.png",
    price: 27.99,
    reviews: 100,
    slug: "eco-friendly-packaging",
    category: "packaging",
  },
];
