export const promotionalProducts = [
  {
    id: 1,
    name: "Custom Mugs",
    desc: "Personalized mugs for promotions, gifts, and corporate use.",
    img: "/promo-img1.png",
    price: 14.99,
    reviews: 120,
    slug: "custom-mugs",
    category: "promotional products",
  },
  {
    id: 2,
    name: "Branded T-Shirts",
    desc: "High-quality T-shirts with your brand logo for giveaways or events.",
    img: "/promo-img2.png",
    price: 24.99,
    reviews: 90,
    slug: "branded-t-shirts",
    category: "promotional products",
  },
  {
    id: 3,
    name: "Keychains",
    desc: "Custom keychains perfect for promotional campaigns and gifts.",
    img: "/promo-img3.png",
    price: 4.99,
    reviews: 150,
    slug: "keychains",
    category: "promotional products",
  },
  {
    id: 4,
    name: "Custom Pens",
    desc: "Stylish pens with your brand logo for corporate giveaways.",
    img: "/promo-img4.png",
    price: 9.99,
    reviews: 130,
    slug: "custom-pens",
    category: "promotional products",
  },
  {
    id: 5,
    name: "Reusable Bags",
    desc: "Eco-friendly reusable bags for promotions or retail use.",
    img: "/promo-img5.png",
    price: 12.99,
    reviews: 100,
    slug: "reusable-bags",
    category: "promotional products",
  },
];
