export const signsBannersPosters = [
  {
    id: 1,
    name: "Outdoor Banners",
    desc: "Durable outdoor banners for events, promotions, and storefronts.",
    img: "/sign-img1.png",
    price: 79.99,
    reviews: 120,
    slug: "outdoor-banners",
    category: "signs and banners",
  },
  {
    id: 2,
    name: "Indoor Posters",
    desc: "High-quality posters for indoor advertising and displays.",
    img: "/sign-img2.png",
    price: 39.99,
    reviews: 95,
    slug: "indoor-posters",
    category: "signs and banners",
  },
  {
    id: 3,
    name: "Vinyl Signs",
    desc: "Custom vinyl signs for businesses, events, and exhibitions.",
    img: "/sign-img3.png",
    price: 59.99,
    reviews: 85,
    slug: "vinyl-signs",
    category: "signs and banners",
  },
  {
    id: 4,
    name: "Roll-up Banners",
    desc: "Portable roll-up banners ideal for trade shows and presentations.",
    img: "/sign-img4.png",
    price: 69.99,
    reviews: 110,
    slug: "roll-up-banners",
    category: "signs and banners",
  },
  {
    id: 5,
    name: "Event Signages",
    desc: "Custom signages for events, conferences, and exhibitions.",
    img: "/sign-img5.png",
    price: 89.99,
    reviews: 75,
    slug: "event-signages",
    category: "signs and banners",
  },
];
