export const stickersLabels = [
  {
    id: 1,
    name: "Custom Logo Stickers",
    desc: "High-quality stickers featuring your brand logo for promotions.",
    img: "/sticker-img1.png",
    price: 19.99,
    reviews: 140,
    slug: "custom-logo-stickers",
    category: "stickers and labels",
  },
  {
    id: 2,
    name: "Product Labels",
    desc: "Durable product labels for packaging, jars, and bottles.",
    img: "/sticker-img2.png",
    price: 14.99,
    reviews: 95,
    slug: "product-labels",
    category: "stickers and labels",
  },
  {
    id: 3,
    name: "Die-Cut Stickers",
    desc: "Unique die-cut stickers for creative branding and giveaways.",
    img: "/sticker-img3.png",
    price: 24.99,
    reviews: 80,
    slug: "die-cut-stickers",
    category: "stickers and labels",
  },
  {
    id: 4,
    name: "Custom Address Labels",
    desc: "Personalized address labels for businesses and personal use.",
    img: "/sticker-img4.png",
    price: 12.99,
    reviews: 65,
    slug: "custom-address-labels",
    category: "stickers and labels",
  },
  {
    id: 5,
    name: "Warning & Safety Labels",
    desc: "Professional warning and safety labels for products and equipment.",
    img: "/sticker-img5.png",
    price: 9.99,
    reviews: 100,
    slug: "warning-safety-labels",
    category: "stickers and labels",
  },
];
